### PR TITLE
Feature/google takeout label priority

### PR DESCRIPTION
**Pull request by poldy79**
Set of two commits to add a feature to upload a google takeout mbox to non gmail imap acounts in a way that makes more sense.

### CODE REVIEW

**Comment by poldy79** [comment]
Please do not merge this pullrequest yet, i found some logic in function begin which does not work properly with other languages than "en" as the translated Strings are beeing used for comparison while all occurences of the label names are already renamed to english values. 

E.g. "Ungelesen" is converted to "Unread", but the label is not beeing detected with languages other than "en" as "Ungelesen" is searched in the label list. I will try to understand this issue before this pull request is merged...

**Comment by poldy79** [comment]
For tests I have switched to a different account - and it seems that this is not "de" but "en". Using "de" on an "en" leads to wrong filtering of labels.

**Comment by rgladwell** [comment]
Sorry for the delay in responding to this. I'm on holiday this week, will try and get back to this next week.

**Comment by rgladwell** [comment]
Is there any update on this, or shall I leave it for a bit?

**Comment by adriangibanelbtactic** [comment]
> Furtermore "Archived" is only selected, if no other label matches - so
> it is a hardcoded low-priority-label.

This being hardcoded is ok with me.

**Comment by poldy79** [comment]
I think it does no harm and perhaps it is handy to have it, altough my need has decerased as I have fixed some tranlations of the Predefined labels (I have to create some more pull requests).

**Comment by rgladwell** [comment]
Thank you for this, if you could resolve the merge conflicts, I'll merge ASAP.

**Comment by rgladwell** [comment]
Thanks!

**Pull request merged**
